### ISSUE TITLE
Highlight name context variables without an @ in front of them in a different color

### ISSUE THREAD

**Issue by dckc** [tgrospic/rholang-idea#4]
see https://rchain.atlassian.net/browse/RHOL-649

cc @KentShikama

**Comment by AbnerZheng** [comment]
This will be solved in https://github.com/tgrospic/rholang-idea/pull/6

**Comment by AbnerZheng** [comment]
Preview: 
![image](https://user-images.githubusercontent.com/7604540/44706469-38f26b00-aad4-11e8-9d48-2678208e0a4e.png)

**Comment by dckc** [comment]
Wow! Nice!

Is it straightforward to put a red squiggle under name vars used in a process context and vice versa?

**Comment by AbnerZheng** [comment]
@dckc No, we use parser to differ from name and process, and assign these PsiElement a different color.

**Comment by dckc** [comment]
Show me how this gets colored?

```
new n in {
  @0!(n) | // different color from above? not as strong a clue as a red squiggle, but perhaps close?
 n!(0)
 }
for (@p <- n) { p!(p) }
```

**Comment by AbnerZheng** [comment]
![image](https://user-images.githubusercontent.com/7604540/44827262-dd93ba80-ac44-11e8-9afa-326699ab991d.png)

**Comment by AbnerZheng** [comment]
@dckc Though the PR is still in review, you can still use the updated version of the plugin by manually install the [plugin](https://rchain.atlassian.net/secure/attachment/10119/rholang-idea.jar) in [this way](https://www.youtube.com/watch?v=fSbpQCGAPL8).
