### ISSUE TITLE
Get "else" highlighted in the same way we do for "if"s

### ISSUE THREAD

**Issue by dckc** [tgrospic/rholang-idea#5]
see https://rchain.atlassian.net/browse/RHOL-648

cc @KentShikama

**Comment by AbnerZheng** [comment]
This will be solved in 
https://github.com/tgrospic/rholang-idea/pull/6

**Comment by AbnerZheng** [comment]
preview:
![image](https://user-images.githubusercontent.com/7604540/44707393-fb431180-aad6-11e8-8e7f-934e5bfb7f04.png)

**Comment by AbnerZheng** [comment]
Thanks @tgrospic .
Since it has been released， I close these two issues.
